### ISSUE TITLE
Templates support

### ISSUE THREAD

**Issue by julianxhokaxhiu** [alfajango/jquery-dynatable#154]
What about supporting some kind of templating function like AngularJS or Ember does?

It's really old school to write HTML inside JS code. it would be much better to have some options that passing an .html file formatted with mustache-like syntax, would just output the JSON data.

Something like this:

``` js
$('#my-table').dynatable({
 'template': {
   'header' : 'path/to/header.html',
   'row' : 'path/to/row.html',
   ...
 }
});
```

_header.html_

``` html
<th>Name</th>
<th>Surname</th>
```

_row.html_

``` html
<td>{ data.name}</td>
<td>{ data.surname}</td>
```

but also something like

_header.html_

``` html
<th>Name Surname</th>
```

_row.html_

``` html
<td>{ data.name} { data.surname}</td>
```

Thanks in advice :) Looking forward for this powerful library.

**Comment by Woolfe** [comment]
Did you end up writing your own workaround?

**Comment by julianxhokaxhiu** [comment]
Phew, this issue was created years ago and I changed totally company during that time. Honestly I never encounter this again since I never had the need to use this library again.

Although I still think would be a great addition :)
