### ISSUE TITLE
ssl certificate expired

### ISSUE THREAD

**Issue by pwim** [alfajango/jquery-dynatable#175]
https://www.dynatable.com/purchase/ has an error because your ssl cert is expired

**Comment by JangoSteve** [comment]
Thank you, we're aware and having issues with our hosting provider updating the certificate. We have a support ticket in to update the server with the new certificate.

**Comment by pwim** [comment]
OK, glad to hear you're already aware of it.

**Comment by JangoSteve** [comment]
Looks like the SSL certificate update has finally gone through in the server settings. Thanks again.
