### ISSUE TITLE
Is this still under active development?

### ISSUE THREAD

**Issue by hugoduraes** [alfajango/jquery-dynatable#179]
Hi guys,

It's been a while since last commit and the latest release was more than a year ago...

So, is this plugin still under active development?

**Comment by JangoSteve** [comment]
Hi @hugoduraes, it's still intended to be under active development, we've just gotten pretty busy lately. We still have a backlog of priorities, and some refactoring and additional features that are partially done and not yet pushed to master. We've given access to a couple other developers to help us build and maintain the project, but they also happen to have become busy lately.

We are still planning to pick development back up and continue with new features.

**Comment by hugoduraes** [comment]
Ok, thank you.
