### ISSUE TITLE
window.history.state is being overwritten

### ISSUE THREAD

**Issue by hugoduraes** [alfajango/jquery-dynatable#180]
Hi,

While working on an app using page.js router, I've noticed that pressing the browser back button to return to a page containing a dynatable with pushState enabled, causes page.js to complain about `window.history.state.path` being undefined.

I guess this happens because Dynatable is overwritting `window.history.state`. I think the issue is in this piece of code:

``` js
cache = { dynatable: { dataset: settings.dataset } };
if (!firstPush) { cache.dynatable.scrollTop = $(window).scrollTop(); }
cacheStr = JSON.stringify(cache);

[...]

try {
    window.history[pushFunction](cache, "Dynatable state", path + params + hash);
} catch(error) {
    // Make cached records = null, so that `pop` will rerun process to retrieve records
    cache.dynatable.dataset.records = null;
    window.history[pushFunction](cache, "Dynatable state", path + params + hash);
}
```

This can be solved extending the object in `cache` variable with `window.history.state` value. Like this:

``` js
cache = { dynatable: { dataset: settings.dataset } };
if (!firstPush) { cache.dynatable.scrollTop = $(window).scrollTop(); }

// added code
$.extend(cache, window.history.state);
// end of added code

cacheStr = JSON.stringify(cache);
```

What do you think?

**Comment by lello1978** [comment]
I have the same problem.... but i cannot identify where to write your solution. Can you identify line number please.
Regards

**Comment by hugoduraes** [comment]
Hi,

You should add the code after line 859 of jquery.dynatable.js file.

WARNING: use the above suggestion at your own risk. I'm not using it and I don't know if it breaks anything else.
