### ISSUE TITLE
CSS Table styling issues

### ISSUE THREAD

**Issue by acidjames** [alfajango/jquery-dynatable#195]
Dear Dynatable,
From what i understand, when i dynatable a table, it resets the css style. Or rather, it applies it's own css style to make it work via Javascript.

I have a very simple table, using bootstrap, with some colored rows.

When i dyna this table, it changes the CSS and makes all the rows white, which is the normal behavior i guess.

How do i keep my colored lines ?

Thanks in advance,
James

btw: thanks for dynatable, it's a great addition to jQuery

**Comment by CaptainCannabis** [comment]
dynatable rewrites the cells - so if you're using classes on those elements they are lost. Try with pure css selectors like "table > tbody > td" or specify your own cell- & rowwriters.
