### ISSUE TITLE
Is dynatable discontinued?

### ISSUE THREAD

**Issue by whenov** [alfajango/jquery-dynatable#238]
The last commit was two years ago.

**Comment by JerryBels** [comment]
Was asking myself the same thing.

**Comment by JangoSteve** [comment]
Wow, two years, that's incredible and I apologize. It's certainly not discontinued; things have just been insanely busy here and so we haven't had the time recently to properly test pull requests and provide feedback for merging and integration. I'll make sure I talk to the team about this and see if we can get someone back on this quickly to try to catch up on the backlog and get this thing humming along again.

**Comment by whenov** [comment]
This is understandable, time is indeed a scarce resource for a business team.

And thanks, We are all looking forward to the revival of this project!
