### ISSUE TITLE
On sort/page change, run function

### ISSUE THREAD

**Issue by afagard** [alfajango/jquery-dynatable#246]
http://stackoverflow.com/questions/37382380/dynatable-on-sort-page-change-run-function

**Comment by dnsBlah** [comment]
Hi I know this ia an older issue, but I'm facing the same issue.

Currently I worked it out using:
 $(".dynatable-sort-header").on('click', function(event) { myfunctioncall here }

Still looking for the page change, This is only working once :-(
$(".dynatable-page-link").on('click', function(event) { myfunctioncall here }

**Comment by afagard** [comment]
Sorry for late reply. But switch to DataTables... way better.
