### ISSUE TITLE
[Feature Request] Add/Edit/Delete records in the table

### ISSUE THREAD

**Issue by markmarucot** [alfajango/jquery-dynatable#25]
This Dynatable has a lot of potential. Is is possible to have a feature that allows Add/Edit/Delete records in the table?

**Comment by Reyncor** [comment]
dynatable.process(true); is a bit of a must use if you previously used a query on the original dynatable. Otherwise you'll get a null error.

```javascript
Uncaught TypeError: Cannot convert undefined or null to object
jquery.dynatable.js:1552 
dt.utility.refreshQueryStringjquery.dynatable.js:817 
pushjquery.dynatable.js:269 
processAlljquery.dynatable.js:148 
dt.processmain.js:119 
removeOrderFromView
```

**Comment by chiquyet199** [comment]
can I add a delete button for every row and how to make this button work?
