### ISSUE TITLE
NS_ERROR_ILLEGAL_VALUE exception in Firefox

### ISSUE THREAD

**Issue by theodorejb** [alfajango/jquery-dynatable#80]
I'm dealing with hundreds of large records, and it seems that the `dataset.originalRecords` array is causing the HTML5 pushstate cache to overrun Firefox's [640k character limit](https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/Manipulating_the_browser_history#The_pushState%28%29.C2.A0method). Might it be better to use localStorage or sessionStorage for this cache, as Mozilla's documentation suggests?

**Comment by JangoSteve** [comment]
Hmm, this was definitely a use-case we had taken into account ([see these line](https://github.com/alfajango/jquery-dynatable/blob/ce207ab5070bf6bf5482d9b4178b2b1b7cc88c98/jquery.dynatable.js#L862-L883)). Are you getting an exception that isn't being caught by the `try/catch` block? Or are you just saying it'd be nice to have a way that doesn't require a try/catch and can still cache the dataset?

**Comment by maksimru** [comment]
Unfortunately NS_ERROR_ILLEGAL_VALUE can't be catched by try / catch so PushState option doesnt work on any large datasets in FF

**Comment by maksimru** [comment]
Small improvement using LZstring compressor (http://pieroxy.net/blog/pages/lz-string/index.html)

in push function

`cache = { dynatable: { dataset: LZString.compress(JSON.stringify(settings.dataset)) } };`

in pop function

`settings.dataset = JSON.parse(LZString.decompress(data.dataset));`

**Comment by mbrodala** [comment]
For us simply disabling the `pushState` feature in dynatable did the trick since we are not using it anyways.

**Comment by lamehost** [comment]
I confirm that disabling `pushState` works
